name: Generate Snake Animation

# Skrip akan berjalan otomatis setiap hari jam 00:00 UTC
on:
  schedule:
    - cron: "0 0 * * *"
  # Memungkinkan Anda menjalankannya secara manual dari tab "Actions"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout repositori
      - uses: actions/checkout@v4

      # Langkah 2: Jalankan aksi Platane/snk
      - uses: Platane/snk@v3
        with:
          github_user_name: David4rr
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Langkah 3: Simpan hasil animasi ke branch 'output'
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
